// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.3.1
// - protoc             v3.21.2
// source: leaf/v1/leaf.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLeafSegment = "/leaf.v1.Leaf/Segment"

type LeafHTTPServer interface {
	Segment(context.Context, *SegmentRequest) (*SegmentReply, error)
}

func RegisterLeafHTTPServer(s *http.Server, srv LeafHTTPServer) {
	r := s.Route("/")
	r.GET("/segment/{key}", _Leaf_Segment0_HTTP_Handler(srv))
}

func _Leaf_Segment0_HTTP_Handler(srv LeafHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SegmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLeafSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Segment(ctx, req.(*SegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SegmentReply)
		return ctx.Result(200, reply)
	}
}

type LeafHTTPClient interface {
	Segment(ctx context.Context, req *SegmentRequest, opts ...http.CallOption) (rsp *SegmentReply, err error)
}

type LeafHTTPClientImpl struct {
	cc *http.Client
}

func NewLeafHTTPClient(client *http.Client) LeafHTTPClient {
	return &LeafHTTPClientImpl{client}
}

func (c *LeafHTTPClientImpl) Segment(ctx context.Context, in *SegmentRequest, opts ...http.CallOption) (*SegmentReply, error) {
	var out SegmentReply
	pattern := "/segment/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLeafSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
